/*
 * SVGTableroTestSuite.java
 * JUnit based test
 *
 * Created on 22 de abril de 2007, 23:28
 */

package svgTablero;

import junit.framework.*;

/**
 *
 * @author Ramon
 */
public class SVGTableroTestSuite extends TestCase {
    
    public SVGTableroTestSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("SVGTableroTestSuite");
        
        suite.addTest(new SVGTableroTest("testSituarTodosEjercitos"));
        return suite;
    }
    
}
