/*
 * modelTestSuite.java
 * JUnit based test
 *
 * Created on 22 de abril de 2007, 22:03
 */

package model;

import junit.framework.*;
import model.TableroTest;

/**
 *
 * @author Ramon
 */
public class modelTestSuite extends TestCase {
    
    public modelTestSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        
        TestSuite suite = new TestSuite("modelTestSuite");
        
        suite.addTest(new TableroTest("testMostrar"));
        suite.addTest(new TableroTest("testGetTodosLosTerritorios"));
        
        
        return suite;
   }
    
}
