/*
 * GlobalSuite.java
 * JUnit based test
 *
 * Created on 21 de abril de 2007, 18:34
 */


import junit.framework.*;
import model.modelTestSuite;
import persistence.persistenceTestSuite;
import svgTablero.SVGTableroTestSuite;

/**
 *
 * @author Ramon
 */
public class GlobalSuite extends TestCase {
    
    public GlobalSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("GlobalSuite");
        
        suite.addTest(new persistenceTestSuite("suite"));
        suite.addTest(new modelTestSuite("suite"));
        suite.addTest(new SVGTableroTestSuite("suite"));
        
        return suite;
    }
    
}
